# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: My_Bazzite
description: Custom gaming OS image for the Steam Deck with RetroDeck, Ryujinx, and autostarting Syncthing.

base-image: ghcr.io/ublue-os/bazzite-deck
image-version: stable 

modules:
  - type: files
    files:
      - source: system
        destination: / 

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - syncthing 
    remove:
      packages:
        - firefox
        - firefox-langpacks 

  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        install: 
          - org.mozilla.firefox
          - org.gnome.Loupe
          - net.retrodeck.retrodeck # Installs RetroDeck system-wide
          - io.github.ryubing.Ryujinx # Installs the active community Ryujinx build
      - scope: user 

  - type: signing
